// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// probability
List probability(S4 cat_df, NumericVector t, IntegerVector q);
RcppExport SEXP catSurv_probability(SEXP cat_dfSEXP, SEXP tSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< S4 >::type cat_df(cat_dfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type q(qSEXP);
    __result = Rcpp::wrap(probability(cat_df, t, q));
    return __result;
END_RCPP
}
// likelihood
double likelihood(S4 cat_df, NumericVector t);
RcppExport SEXP catSurv_likelihood(SEXP cat_dfSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< S4 >::type cat_df(cat_dfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    __result = Rcpp::wrap(likelihood(cat_df, t));
    return __result;
END_RCPP
}
// estimateTheta
double estimateTheta(S4 cat_df);
RcppExport SEXP catSurv_estimateTheta(SEXP cat_dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< S4 >::type cat_df(cat_dfSEXP);
    __result = Rcpp::wrap(estimateTheta(cat_df));
    return __result;
END_RCPP
}
// estimateSE
double estimateSE(S4 cat_df);
RcppExport SEXP catSurv_estimateSE(SEXP cat_dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< S4 >::type cat_df(cat_dfSEXP);
    __result = Rcpp::wrap(estimateSE(cat_df));
    return __result;
END_RCPP
}
// prior
double prior(NumericVector x, CharacterVector c, NumericVector p);
RcppExport SEXP catSurv_prior(SEXP xSEXP, SEXP cSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type c(cSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    __result = Rcpp::wrap(prior(x, c, p));
    return __result;
END_RCPP
}
