# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Find the weighted mean of several normal distributions
#' 
#' @param x A vector of values where the weighted normal is being evaluated
#' @param means The means of the vaious normal distributions
#' @param weights The weight assigned to each normal distribution
#' @param sd A single number for the common standard deviation
#' @export
probability <- function(cat_df, t, q) {
    .Call('catSurv_probability', PACKAGE = 'catSurv', cat_df, t, q)
}

