# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Probabilities of the responses to a question given theta
#'
#' This function calculates the probabilities of a specific set of responses to a specific question for a specific value of \eqn{\theta}.
#'
#' @param cat_df An object of \code{Cat} class
#' @param t A double indicating the potential value for \eqn{\theta_j}
#' @param q An integer indicating the index of the question
#' @param ret_prob (For polytonomous implementation only) A double-vector where the calculations carried out by this function will be stored.
#'
#' @return A vector consisting of the probability of a correct response for each respondent on item \eqn{i}.
#'
#' @details The probability of a correct response for respondent \eqn{j} on item \eqn{i} is ....
#' where \eqn{\theta_j} is respondent \eqn{j}'s position on the latent scale of interest, \eqn{a_i} is item \eqn{i}'s discrimination parameter,
#'  \eqn{b_i} is item i's difficulty parameter, and \eqn{c_i} is item \eqn{i}'s guessing parameter.
#'
#'  Note: this function is overloaded, due to different output types of binary vs polytomous implementations (outputs single value for binary implementation,
#'  vector of values for polytomous implementation)
#'
#'  Note: the function for polytomous implementation does not return values, but rather alters the object ret_prob in memory
#'
#' @export
probability <- function(cat_df, t, q) {
    .Call('catSurv_probability', PACKAGE = 'catSurv', cat_df, t, q)
}

#' @export
showCppCat <- function(cat_df) {
    invisible(.Call('catSurv_showCppCat', PACKAGE = 'catSurv', cat_df))
}

#' Likelihood of offering specific response
#'
#' This function returns the value of likelihood of a person with ability parameter \eqn{\theta} having offered the specific response profile stored in answers conditional on the item-level parameters.
#'
#' @param cat_df An object of \code{Cat} class
#' @param t A numeric for possible value of theta (position on the latent scale of interest)
#'
#' @return A value of the likelihood of each respondent having offered the provided response profile
#'
#' @details Letting \eqn{q_i(\theta_j)=1-p_i(\theta_j)}, the likelihood function associated with the responses profile \eqn{y_j} is..
#' \eqn{L(\theta_j|\mathbf{y}_{j})=\prod^{j}_{i=1}p_i(\theta_j)^{y_{ij}}q_i(\theta_j)^{(1-y_{ij}}}, where \eqn{y_j} is evaluated based only on the questions the respondent has actually had the opportunity to answer
#'
#' @export
likelihood <- function(cat_df, t) {
    .Call('catSurv_likelihood', PACKAGE = 'catSurv', cat_df, t)
}

#' Estimate of the ability parameter
#'
#' This function takes a Cat object and returns the expected value of the ability parameter conditioned on the observed answers and the item calibrations.
#'
#' @param cat An object of \code{Cat} class
#'
#' @return A vector consisting of the expected value of the ability parameter
#'
#' @details The expected value of \eqn{\theta_j} is:
#' \eqn{\frac{\int_{-\infty}^\infty \theta_j \eqn{L}(\theta_j) \pi(\theta_j) d\theta_j}{\int_{-\infty}^\infty \eqn{L}(\theta_j) \pi(\theta_j) d\theta_j}},
#' where \eqn{L}(\theta_j) is the likelihood function and \pi(\theta_j) is the prior distribution for \eqn{\theta_j}
#'
#'
#'  Note: When MLE would not work, estimateTheta is calculated according to the estimationDefault slot in Cat object.
#'
#'  Note: This method will only be available using the normal prior distribution
#'
#' @export
estimateTheta <- function(cat_df) {
    .Call('catSurv_estimateTheta', PACKAGE = 'catSurv', cat_df)
}

#' Estimate of standard error for the posterior estimate
#'
#' This function estimates the standard error for the posterior estimate for the position \eqn{\theta_j} of a person on the latent scale
#'
#' @param cat An object of \code{Cat} class
#'
#' @return The posterior standard error for \eqn{\theta_j}
#'
#' @details The posterior variance for \eqn{\theta_j} is:
#' \eqn{\hat{\theta}_j = E[(\theta_j-\hat{\theta_j})^2]=\frac{\int(\theta_j-\hat{\theta_j})^2\pi(\theta_j)L(\theta_j)d\theta_j}{}\int\pi(\theta_j)L(\theta_j)d\theta_j},
#' where \eqn{\hat{\theta}_j} is the chosen point estimate for the respondent on the latent scale. The standard error is then \sqrt{\mbox{Var}(\hat{\theta}_j)}
#'
#'
#' @export
estimateSE <- function(cat_df) {
    .Call('catSurv_estimateSE', PACKAGE = 'catSurv', cat_df)
}

#' The possible prior distribution functions
#'
#' This function returns the prior value for each respondent's position on the latent scale of interest
#'
#' @param x A numeric value where we want to evaluate the prior name
#'
#' @return A vector consisting of prior value, \eqn{\pi(x)}, given the value \eqn{x}
#'
#' @details \eqn{x} needs to be either NORMAL or STUDENT_T params, which are parameters controlling the shape of the prior
#'
#' @export
prior <- function(x, c, p) {
    .Call('catSurv_prior', PACKAGE = 'catSurv', x, c, p)
}

#' @export
dLL <- function(cat_df, theta, use_prior) {
    .Call('catSurv_dLL', PACKAGE = 'catSurv', cat_df, theta, use_prior)
}

#' @export
d2LL <- function(cat_df, theta, use_prior) {
    .Call('catSurv_d2LL', PACKAGE = 'catSurv', cat_df, theta, use_prior)
}

#' @export
selectItem <- function(cat_df) {
    .Call('catSurv_selectItem', PACKAGE = 'catSurv', cat_df)
}

#' @export
lookAhead <- function(cat_df, item) {
    .Call('catSurv_lookAhead', PACKAGE = 'catSurv', cat_df, item)
}

#' @export
expectedPV <- function(cat_df, item) {
    .Call('catSurv_expectedPV', PACKAGE = 'catSurv', cat_df, item)
}

#' @export
obsInf <- function(cat_df, theta, item) {
    .Call('catSurv_obsInf', PACKAGE = 'catSurv', cat_df, theta, item)
}

#' @export
fisherInf <- function(cat_df, theta, item) {
    .Call('catSurv_fisherInf', PACKAGE = 'catSurv', cat_df, theta, item)
}

#' @export
expectedObsInf <- function(cat_df, item) {
    .Call('catSurv_expectedObsInf', PACKAGE = 'catSurv', cat_df, item)
}

#' @export
kl <- function(cat_df, item) {
    .Call('catSurv_kl', PACKAGE = 'catSurv', cat_df, item)
}

#' @export
findRoot <- function(cat_df) {
    .Call('catSurv_findRoot', PACKAGE = 'catSurv', cat_df)
}

